#ifndef CA_CERT_H
#define CA_CERT_H

static const char ca_cert_pem[] = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDljCCAx2gAwIBAgISBlN/NWm4HY1b6ZBC5WmBqGoLMAoGCCqGSM49BAMDMDIx\n" \
"CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF\n" \
"NzAeFw0yNTA4MjAyMDQ3MzlaFw0yNTExMTgyMDQ3MzhaMBcxFTATBgNVBAMTDGhh\n" \
"Y2thZGF5LmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBjkVzmo6V6Ijnk+\n" \
"qr7SXB0jkJtNEBPSt6yNmK3ItTpArsJghUdkNgZmjhFj/KrKxyJ6VIINhib0EQxo\n" \
"BgGsyqyjggIsMIICKDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUH\n" \
"AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFL40oVFWrv0FAZ9D\n" \
"MQnk0SEqNAHBMB8GA1UdIwQYMBaAFK5IntyHHUSgb9qi5WB0BHjCnACAMDIGCCsG\n" \
"AQUFBwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL2U3LmkubGVuY3Iub3JnLzAp\n" \
"BgNVHREEIjAgggxoYWNrYWRheS5jb22CEHd3dy5oYWNrYWRheS5jb20wEwYDVR0g\n" \
"BAwwCjAIBgZngQwBAgEwLQYDVR0fBCYwJDAioCCgHoYcaHR0cDovL2U3LmMubGVu\n" \
"Y3Iub3JnLzEyLmNybDCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB2AO08S9boBsKk\n" \
"ogBX28sk4jgB31Ev7cSGxXAPIN23Pj/gAAABmMlyVTAAAAQDAEcwRQIgSHeF1+Hg\n" \
"ecX9rzwrIwb0327Uzk8h9qVTTvRwOIFbrTsCIQCEXUdOzIQFoGHxYyeumJrc/UTT\n" \
"BHG/rdbbCg7JuGNVrAB2ABLxTjS9U3JMhAYZw48/ehP457Vih4icbTAFhOvlhiY6\n" \
"AAABmMlyVTYAAAQDAEcwRQIhALQdWRItA6aJiKDcMPso/i5xEkfcEN+WxkB4cdRv\n" \
"Qk71AiBjWtzlIcyaMCaXsiahq+6ARRH4nIah2ak5c2LX/H52ZDAKBggqhkjOPQQD\n" \
"AwNnADBkAjBbjlEitSH2Zk1EsarrSMIAM5F1sJRVAAIAJxdU/bDSzz00XQhX41xW\n" \
"IjrH81EjY7QCMCWTQqunyLmYs+XQFqo4d9qE2+2BVpVi39Hb82l1Npn7+cY3yx3b\n" \
"h358ltnTRKFwDg==\n" \
"-----END CERTIFICATE-----\n" \
"-----BEGIN CERTIFICATE-----\n" \
"MIIEVzCCAj+gAwIBAgIRAKp18eYrjwoiCWbTi7/UuqEwDQYJKoZIhvcNAQELBQAw\n" \
"TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n" \
"cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw\n" \
"WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg\n" \
"RW5jcnlwdDELMAkGA1UEAxMCRTcwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARB6AST\n" \
"CFh/vjcwDMCgQer+VtqEkz7JANurZxLP+U9TCeioL6sp5Z8VRvRbYk4P1INBmbef\n" \
"QHJFHCxcSjKmwtvGBWpl/9ra8HW0QDsUaJW2qOJqceJ0ZVFT3hbUHifBM/2jgfgw\n" \
"gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD\n" \
"ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSuSJ7chx1EoG/aouVgdAR4\n" \
"wpwAgDAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB\n" \
"AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g\n" \
"BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu\n" \
"Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAjx66fDdLk5ywFn3CzA1w1qfylHUD\n" \
"aEf0QZpXcJseddJGSfbUUOvbNR9N/QQ16K1lXl4VFyhmGXDT5Kdfcr0RvIIVrNxF\n" \
"h4lqHtRRCP6RBRstqbZ2zURgqakn/Xip0iaQL0IdfHBZr396FgknniRYFckKORPG\n" \
"yM3QKnd66gtMst8I5nkRQlAg/Jb+Gc3egIvuGKWboE1G89NTsN9LTDD3PLj0dUMr\n" \
"OIuqVjLB8pEC6yk9enrlrqjXQgkLEYhXzq7dLafv5Vkig6Gl0nuuqjqfp0Q1bi1o\n" \
"yVNAlXe6aUXw92CcghC9bNsKEO1+M52YY5+ofIXlS/SEQbvVYYBLZ5yeiglV6t3S\n" \
"M6H+vTG0aP9YHzLn/KVOHzGQfXDP7qM5tkf+7diZe7o2fw6O7IvN6fsQXEQQj8TJ\n" \
"UXJxv2/uJhcuy/tSDgXwHM8Uk34WNbRT7zGTGkQRX0gsbjAea/jYAoWv0ZvQRwpq\n" \
"Pe79D/i7Cep8qWnA+7AE/3B3S/3dEEYmc0lpe1366A/6GEgk3ktr9PEoQrLChs6I\n" \
"tu3wnNLB2euC8IKGLQFpGtOO/2/hiAKjyajaBP25w1jF0Wl8Bbqne3uZ2q1GyPFJ\n" \
"YRmT7/OXpmOH/FVLtwS+8ng1cAmpCujPwteJZNcDG0sF2n/sc0+SQf49fdyUK0ty\n" \
"+VUwFj9tmWxyR/M=\n" \
"-----END CERTIFICATE-----\n" \
;

#endif // CA_CERT_H
